name: Epic Games Notifier

on:
  schedule:
    # יריץ את הבוט בכל יום חמישי בשעה 18:30 שעון ישראל (16:30 UTC)
    - cron: '30 16 * * 4'
  workflow_dispatch: # מאפשר לך להריץ את הבוט ידנית מתי שתרצה

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python script.py
